#!/bin/bash
clang -v 2> /dev/null
if [[ $? != 0 ]] ; then
  echo "you have to install clang"
  exit 1
fi

if [[ -z $MUSL ]] ; then
  echo "export MUSL=/path/to/musl"
  echo "\$MUSL/lib must containt libc.a"
  exit 1
fi
echo "dependencies met"
